# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'detox51' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for detox51
pod "CleverTap-iOS-SDK"
  target 'detox51-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'detox51Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

